### ISSUE TITLE
can't seem to get it on blender with 3.0 :( 

### ISSUE THREAD

**Issue by M88S** [ranjian0/building_tools#199]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ranjian0** [comment]
Are you using the latest version?

**Comment by jwh1981** [comment]
I am using Blender 3.0.1. I just downloaded the latest snapshot of master and I only have the option to create a floorplan. The options for Add Floors, Add Roof, etc. are all greyed out. I am unsure if this is the issue the OP is having but I wanted to add to this issue instead of creating a new one.

**Comment by jwh1981** [comment]
To elaborate, clicking in Create Floorplan works but then I cannot Add Floors, etc.

**Comment by ranjian0** [comment]
You need to be in edit mode for other tools to work. 

https://github.com/ranjian0/building_tools/wiki/Usage

**Comment by jwh1981** [comment]
100% my issue. Thank you very much, edit mode is what I needed and I'm good now.

**Comment by ranjian0** [comment]
I will close this now. Feel free to open another issue if you ran into more problems. Thanks.
